package:
  name: openmmmcmc-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm-dev
    - numpy
    - scipy
    - openmoltools-dev
    - openmmtools
    - pymbar

  run:
    - python
    - openmm-dev
    - numpy
    - scipy
    - openmoltools-dev
    - openmmtools
    - pymbar

test:
  requires:
    - nose
    - openmmtools
    - pymbar
  imports:
    - openmmmcmc

about:
  home: https://github.com/choderalab/openmmmcmc
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
